### ISSUE TITLE
Path too long to unzip

### ISSUE THREAD

**Issue by LedaguenelArthur** [linqs/visual-sudoku-puzzle-classification#1]
Hi,

I have downloaded a dataset from this Github repository which arrived in a zip format.

But now I can't get the `ViSudo-PC` folder out of its zip folder because Windows tells me the path `tmp/ViSudo-PC/ViSudo-PC_dimension::4_datasets::mnist_strategy::simple/dimension::4/datasets::mnist/strategy::simple/strategy::simple/numTrain::00001/numTest::00100/numValid::00100/corruptChance::0.50/overlap::0.00/` is too long.

Any clues on how to circumvent that ? Should I just try to unzip the `numValid::00100` folder directly ?

Best regards,
Arthur

**Comment by eriq-augustine** [comment]
What OS are you using?

Regardless of OS, a simple thing you can try is unzipping in a directory that already has a short path (like `/tmp`).

**Comment by LedaguenelArthur** [comment]
Hi @eriq-augustine,

I'm using Windows 10 Professional.

Ok I'll try that thanks ;-)

**Comment by eriq-augustine** [comment]
Looks like on Windows, there is a pretty short limit by default (260), but you can tell Windows to allow longer paths:
https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry#enable-long-paths-in-windows-10-version-1607-and-later

**Comment by eriq-augustine** [comment]
(I don't use Windows, so I probably can't help with all the fine details there.)

**Comment by LedaguenelArthur** [comment]
Ok thanks a lot !

**Comment by eriq-augustine** [comment]
I'm going to close this up.
Let me know if you are still having issues and I can re-open.
