### ISSUE TITLE
PyTorch Dataloading

### ISSUE THREAD

**Issue by LedaguenelArthur** [linqs/visual-sudoku-puzzle-classification#2]
Hi,

I am trying to train a PyTorch model on VSPC. I have downloaded a version of the dataset from this repo but I am not sure how to interface this with standard PyTorch Dataset and Dataloader objects.

Do you have a quick demo on how to read the data repository with standard PyTorch utilitaries ?

Best regards,
Arthur

**Comment by eriq-augustine** [comment]
Sorry, I don't have any experience with PyTorch.
Since the data is just TSV, I hope it should be pretty easy to load up into whatever libraries you are using.

**Comment by eriq-augustine** [comment]
I'm going to close this up.
Let me know if you are still having issues and I can re-open.
